// src/components/ChordSelection/ChordSelection.svelte
<script lang="ts">
  import { ChordSet } from "../../Utils/Music/ChordSet";
  import ChordChoice from './ChordChoice.svelte';
  import {intervalSet, selectedChords} from '../../store';

  const showAll = () => selectedChords.set(ChordSet.fromAllChords);
  const showDefault = () => selectedChords.set(ChordSet.fromDefaultChords);
  
  $: defaultChordsAreSelected = $selectedChords.equals(ChordSet.fromDefaultChords);
  $: chordsInScale = ChordSet.fromContainingIntervalSet($intervalSet).chords;
</script>

<div id='chord-selection'>

  <div class='heading'>
    <h2>Chords in scale</h2>
    <div class='togglers'>
      {#if defaultChordsAreSelected}
        <span on:click={showAll}>Show all</span>
      {:else}
        <span on:click={showDefault}>Show default</span>
      {/if}
    </div>
  </div>

  <div class='chord-choices'>
    {#each chordsInScale as chord (chord.binary)}
      <ChordChoice {chord} isSelected={$selectedChords.containsChord(chord)} />
    {/each}
  </div>

</div>

<style>
  #chord-selection {overflow: scroll;}
  .heading {
    display: flex;
    align-items: baseline;
    align-content: center;
    justify-content: center;
    flex-wrap: wrap;
  }
  .heading > * { margin: 0 1vmax 0.5vmax 1vmax; }
  .togglers span {font-style: italic;}
  .chord-choices {display: flex; flex-wrap: wrap; justify-content: center;}
</style>

// src/components/Menu/ChordSelection.tsx
import React from "react";
import styled from 'styled-components';
import { ChordSet } from "../../Utils/Music/ChordSet";
import { ChordChoices } from "./ChordChoices";
import { IntervalSet } from "../../Utils/Music/IntervalSet";
import { Chord } from "../../Utils/Music/Chord";

const Heading = styled.div`
  display: flex;
  align-items: baseline;
  align-content: center;
  justify-content: center;
  flex-wrap: wrap;
  & > * {
    margin: 0 1vmax 0.5vmax 1vmax;
  }
`;

const StyledA = styled.a`
  font-style: italic;
`;

interface Props {
  className?: string;
  setChordSet(cs: ChordSet): void;
  selectedChords: ChordSet;
  intervalSet: IntervalSet;
  toggleChord(c: Chord): void;
}

export function ChordSelection(props: Props) {
  const defaultChordsAreSelected =
    props.selectedChords.equals(ChordSet.fromDefaultChords);
  return (
    <div className={props.className}>
      <Heading>
        <h2>Chords in scale</h2>
        { defaultChordsAreSelected &&
          <StyledA
            onClick={e => props.setChordSet(ChordSet.fromAllChords)}
          >
            show all
          </StyledA>
        }
        { !defaultChordsAreSelected &&
          <StyledA
            onClick={e => props.setChordSet(ChordSet.fromDefaultChords)}
          >
            Show default
          </StyledA>
        }
      </Heading>
      <ChordChoices
        selectedChords={props.selectedChords}
        toggleChord={props.toggleChord}
        intervalSet={props.intervalSet}
      />
    </div>
  );
}
