// src/components/Wheel/Scale/ChordInScale.svelte
<script lang="ts">
  import { Chord } from '../../../Utils/Music/Chord';
  import { IrPoint } from '../../../Utils/Geometry/IrPoint';
  import { Note } from '../../../Utils/Music/Note';
  import ChordEmblem from '../../common/ChordEmblem.svelte';
  import { somethingIsRotating } from '../Wheel.svelte';
  import Key from '../../Keyboard/Key.svelte';
  import { Scalar } from '../../../Utils/Math/Scalar';
  import {getStore} from '../../../store';
  const {editVsPlay} = getStore();

  let className: string | undefined = undefined;
  export {className as class};
  export let interval: number;
  export let note: Note | undefined = undefined;
  export let chord: Chord;
  export let radialPosition: number;
  export let size: number;

  $: pitches = chord.ordinals.map(ordinal => {
    const noteId = Scalar.wrapToOctave(ordinal + (note?.id || 0));
    return (new Note(noteId)).pitchInOctave(4);
  });

  $: displayNoteName = !$somethingIsRotating;
  $: noteName = displayNoteName ? (note?.name?.unicode || '') : undefined;
  $: transform = (() => {
    const {x, y} = new IrPoint(interval, radialPosition).toXy();
    return `translate(${x} ${y})`;
  })();
  $: isClickable = $editVsPlay === 1;

</script>

<g class:isClickable {transform} class={className} >
  <!-- 
    This "background" circle is here and filled solid because the chord
    emblem becomes translucent during editing and needs a background to
    separate it from the other emblems.
  -->
  <circle class='background' cx={0} cy={0} r={size} />
  <ChordEmblem {size} {chord} {noteName} opacity={isClickable ? 1 : 0.4} />
  <Key {pitches} isInsideSvg={true} >
    <circle class='touch-receptor' cx={0} cy={0} r={size} />
  </Key>
</g>

<style>
  g > :global(.background) {
    stroke: #e1e1e1;
    fill: #e1e1e1;
  }
  g > :global(.background),
  g :global(.touch-receptor) {
    stroke-width: 5px;
  }
  g :global(.touch-receptor) {
    visibility: hidden;
  }
</style>

// src/components/Wheel/Scale/ChordInScale.tsx
import React from 'react';
import styled from 'styled-components';
import { OrdinalChord } from '../../../Utils/Music/OrdinalChord';
import { Chord } from '../../../Utils/Music/Chord';
import { IrPoint } from '../../../Utils/Geometry/IrPoint';
import { Angle } from '../../../Utils/Geometry/Angle';
import { ChordEmblem } from '../../common/ChordEmblem';
import { useStore } from '../../Store';
import { observer } from 'mobx-react-lite';
import { Note } from '../../../Utils/Music/Note';

const Background = styled.circle`
  stroke: #e1e1e1;
  stroke-width: 5px;
`;

const ClickableG = styled.g`
  & * {
    cursor: pointer;
  }
  &:hover ${Background} {
    stroke: white;
    stroke-width: 15px;
  }
`;

const NonClickableG = styled.g`
  & * {
    cursor: grab;
  }
`;

interface Props {
  interval: number;
  note?: Note;
  chord: Chord;
  radialPosition: number;
  rotation: number;
  className?: string;
  size: number;
}

export const ChordInScale = observer((props: Props) => {
  const store = useStore();
  const displayNoteName = !store.scaleIsRotating && !store.keyboardIsRotating;
  const noteName = displayNoteName ? (props.note?.name?.unicode || '') : '';
  type GenericEvent = React.MouseEvent | React.TouchEvent;
  const handleMouseDownOrTouchStart = (event: GenericEvent) => {
    event.preventDefault();
    const ordinalChord = new OrdinalChord(
      props.interval, props.chord
    );
    store.playOrdinalChord(ordinalChord);
    event.stopPropagation();
  }

  const transform = (() => {
    const point = new IrPoint(props.interval, props.radialPosition).toXy();
    const rotation = -Angle.iToD(props.rotation);
    return `translate(${point.x} ${point.y}) rotate(${rotation})`;
  })();

  const clickable = store.editVsPlay === 1;
  const G = clickable ? ClickableG : NonClickableG;

  return (
    <G
      transform={transform}
      opacity={store.editVsPlay === 1 ? 1 : 0.4}
      className={props.className}
      onMouseDown={clickable ? handleMouseDownOrTouchStart : undefined}
      onTouchStart={clickable ? handleMouseDownOrTouchStart : undefined}
      onTouchEnd={clickable ? e => e.preventDefault() : undefined}
    >
      <Background cx={0} cy={0} r={props.size} />
      <ChordEmblem
        size={props.size}
        chord={props.chord}
        noteName={noteName}
      />
    </G>
  );

})
