// src/components/Wheel/RotaryKeyboard/KeyPolygon.svelte
<script lang="ts">
  import { Scalar } from '../../../Utils/Math/Scalar';
  import { IrPoint } from '../../../Utils/Geometry/IrPoint';
  import Polygon from '../common/Polygon.svelte';
  import { keyboardRadius } from '../../../store';

  let className = undefined as string | undefined;
  export {className as class};
  export let interval: number;

  $: innerRadius = $keyboardRadius - 131;
  $: shape = [
    [-0.5, $keyboardRadius * Scalar.rFactorAtEdge],
    [0, $keyboardRadius],
    [0.5, $keyboardRadius * Scalar.rFactorAtEdge],
    [0.5, innerRadius * Scalar.rFactorAtEdge],
    [0, innerRadius],
    [-0.5, innerRadius * Scalar.rFactorAtEdge],
  ] as [number, number][];
  $: points = shape.map(ir =>
    IrPoint.fromArray(ir).plusI(interval)
  );
</script>

<Polygon points={points} class={className}/>

// src/components/Wheel/Keyboard/common/KeyPolygon.tsx
import React from 'react';
import { Scalar } from '../../../../Utils/Math/Scalar';
import { IrPoint } from '../../../../Utils/Geometry/IrPoint';
import { Polygon } from '../../common/Polygon';
import { Pitch } from '../../../../Utils/Music/Pitch';

const innerRadius = 308;
const outerRadius = 400;

interface Props {
  pitch: Pitch;
  className: string;
}

export function KeyPolygon(props: Props) {
  const shape: [number, number][] = [
    [-0.5, outerRadius * Scalar.rFactorAtEdge],
    [0, outerRadius],
    [0.5, outerRadius * Scalar.rFactorAtEdge],
    [0.5, innerRadius * Scalar.rFactorAtEdge],
    [0, innerRadius],
    [-0.5, innerRadius * Scalar.rFactorAtEdge],
  ];
  const points = shape.map(ir =>
    IrPoint.fromArray(ir).plusI(props.pitch.note.id)
  );
  return <Polygon points={points} className={props.className}/>;
}
