// src/components/Wheel/common/Polygon.tsx
import React from 'react';
import { XyPoint } from './../../../Utils/Geometry/XyPoint';
import { IrPoint } from '../../../Utils/Geometry/IrPoint';

interface Props {
  points: IrPoint[];
  className?: string;
  fill?: string;
  opacity?: string | number;
}

export function Polygon(props: Props) {
  let pointsString = XyPoint.stringFromIrArray(props.points);
  return <polygon
    className={props.className}
    points={pointsString}
    fill={props.fill}
    opacity={props.opacity}
  />;
}

// src/components/Wheel/common/Polygon.svelte
<script lang="ts">
  import { XyPoint } from './../../../Utils/Geometry/XyPoint';
  import { IrPoint } from '../../../Utils/Geometry/IrPoint';
  
  let className: string | undefined = undefined;
  export {className as class};
  export let points: IrPoint[];
  export let fill: string | undefined = undefined;
  export let opacity = 1;
  
  let pointsString = XyPoint.stringFromIrArray(points);
</script>

<polygon points={pointsString} {fill} {opacity} class={className} />
