// src/components/common/Button.tsx
import React from 'react';
import styled from 'styled-components';
import {FontAwesomeIcon} from '@fortawesome/react-fontawesome'

const StyledA = styled.a`
  padding: 0.4vmax 0.7vmax;
  border-radius: 0.4vmax;
  background: #f2f2f2;
  border: solid 0.1vmax #bcbcbc;
  cursor: pointer;
  display: inline-block;
  line-height: 1.7vmax;
  text-align: center;
  outline: none;
  color: black;
  text-decoration: none;
  &:hover {
    text-decoration: underline;
    background-color: white;
  }
`;

export default function Button(props) {
  const content = props.label || props.children;
  return (
    <StyledA {...props}>
      <div>
        { props.icon &&
          <FontAwesomeIcon icon={props.icon} color={'#454545'} />
        }
      </div>
      <div>{content}</div>
    </StyledA>
  )
}

// src/components/Toolbar/Button.svelte
<script lang='ts'>
  export let icon = undefined as any;
</script>

<div class='button' on:click >
  {#if icon}<div class='icon'><svelte:component this={icon} /></div>{/if}
  <div><slot /></div>
</div>

<style>
  .button {
    display: inline-block;
    padding: 0.2em 0.4em;
    border-radius: 0.4em;
    background: #f2f2f2;
    border: solid 0.05em #bcbcbc;
    cursor: pointer;
    line-height: 1em;
    text-align: center;
    outline: none;
    color: black;
    display: flex;
    flex-direction: column;
    justify-content: center;
    align-items: center;
  }
  .button > * {margin: 0.2em;}
  .icon {
    height: 2em;
    width: 2em;
  }
</style>
