// src/components/Wheel/BlurFilter.svelte
<script lang="ts">

</script>

<!-- import React from 'react';

interface Props {
  bounds?: number;
  id?: string;
  size: number;
}

export function BlurFilter(props: Props) {
  const bounds = props.bounds || 1.2;
  return (
    <filter
      id={props.id}
      x={-(bounds - 1) / 2}
      y={-(bounds - 1) / 2}
      width={bounds}
      height={bounds}
    >
      <feGaussianBlur in="SourceGraphic" stdDeviation={props.size}/>
    </filter>
  );
} -->

// src/components/Wheel/BlurFilter.tsx
import React from 'react';

interface Props {
  bounds?: number;
  id?: string;
  size: number;
}

export function BlurFilter(props: Props) {
  const bounds = props.bounds || 1.2;
  return (
    <filter
      id={props.id}
      x={-(bounds - 1) / 2}
      y={-(bounds - 1) / 2}
      width={bounds}
      height={bounds}
    >
      <feGaussianBlur in="SourceGraphic" stdDeviation={props.size}/>
    </filter>
  );
}
