// src/components/App.tsx
import React from "react";
import { library } from '@fortawesome/fontawesome-svg-core'
import { faPlus, faMinus, faMusic, faCaretLeft, faCaretRight }
  from '@fortawesome/free-solid-svg-icons'
import {faGithub} from '@fortawesome/free-brands-svg-icons'
import { RouteProcessor } from "./RouteProcessor";
import { Layout } from "./Layout";
import { StoreProvider } from "./Store";
import { Url } from './../Utils/Text/Url';

library.add(faPlus, faMinus, faMusic, faCaretLeft, faCaretRight,
  faGithub);

export default function App() {
  let initialValuesFromUrl = Url.parse(window.location.pathname);

  return (
    <StoreProvider initialValues={initialValuesFromUrl} >
      <>
        <RouteProcessor/>
        <Layout/>
      </>
    </StoreProvider>
  );
}

// src/components/App.svelte
<script lang="ts">
  // import { RouteProcessor } from "./RouteProcessor";
  import Layout from "./Layout.svelte";
  // import { StoreProvider } from "./Store";
  // import { Url } from './../Utils/Text/Url';
  // import { useAudio } from "./useAudio";

  // let initialValuesFromUrl = Url.parse(window.location.pathname);
  // const audio =  useAudio();

</script>

<!-- <StoreProvider initialValues={initialValuesFromUrl} audio={audio} > -->
    <!-- <RouteProcessor/> -->
    <Layout/>
<!-- </StoreProvider> -->
