// src/components/Wheel/RotaryKeyboard/KeySet.svelte
<script lang="ts">
  import type { NoteSet } from "../../../Utils/Music/NoteSet";
  import RotaryKey from "./RotaryKey.svelte";
  export let noteSet: NoteSet;
  export let isActive: boolean;
</script>

<g filter={isActive ? "url('#shadow-when-play')" : 'none'}>
  {#each noteSet.notes as note (note.id)}
    <RotaryKey {note} {isActive} />
  {/each}
</g>

// src/components/Wheel/Keyboard/KeySet.tsx
import React from "react";
import { PitchSet } from "../../../Utils/Music/PitchSet";
import { Key } from "./Key";

interface Props {
  pitchSet: PitchSet;
  active: boolean;
  rotation: number;
}

export function KeySet(props: Props) {
  const pitches = props.pitchSet.pitches;
  const keys = pitches.map(pitch =>
    <Key
      key={pitch.note.id}
      pitch={pitch}
      rotation={props.rotation}
      active={props.active}
    />
  );
  const filter = props.active ? "url('#shadow-when-play')" : undefined;
  return <g filter={filter}>{keys}</g>;
}
